### ISSUE TITLE
.git directory reported missing on CI builds

### ISSUE THREAD

**Issue by stephenplatz** [doctrine/deprecations#42]
I'm suddenly having an issue with my CI builder failing with a runtime exception

The .git directory is missing from /builds/path/to/project/vendor/doctrine/deprecations, see https://getcomposer.org/commit-deps for more information

I've not seen this before, and I noticed that a release was just published, so I'm wondering if there could be a connection.

**Comment by greg0ire** [comment]
It's probably related, but you're giving us very little to work with. If you were us, what more detail would you wish to have to debug this? Right now, all I can tell is that this line of code is probably the one being called: https://github.com/composer/composer/blob/7528c86e58884f5676d5851d52cd94c67372d609/src/Composer/Downloader/GitDownloader.php#L161

**Comment by stephenplatz** [comment]
Makes sense. Here's the output just prior to the error, which really doesn't tell us very much either

`composer install --no-interaction
Gathering patches for root package.
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 1 install, 9 updates, 0 removals
  - Syncing doctrine/deprecations (v1.1.0) into cache
  - Syncing politsin/jquery-ui-touch-punch (1.0) into cache
  - Syncing drupal/jquery_ui (1.6.0) into cache
  - Syncing drupal/jquery_ui_touch_punch (1.1.0) into cache
  - Syncing drupal/jquery_ui_slider (2.0.0) into cache
  - Syncing drupal/jquery_ui_datepicker (2.0.0) into cache
  - Syncing drupal/better_exposed_filters (6.0.3) into cache
  - Syncing drupal/colorbox (2.0.1) into cache
  - Syncing drupal/jquery_ui_checkboxradio (2.0.0) into cache
  - Syncing drupal/search_api (1.29.0) into cache
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Upgrading doctrine/deprecations (v1.0.0 => v1.1.0):     Update of doctrine/deprecations failed
  - Installing politsin/jquery-ui-touch-punch (1.0): Cloning 2fe375e058 from cache
  - Upgrading drupal/jquery_ui (1.4.0 => 1.6.0):     Update of drupal/jquery_ui failed
  - Upgrading drupal/jquery_ui_touch_punch (1.0.0 => 1.1.0):     Update of drupal/jquery_ui_touch_punch failed
  - Upgrading drupal/jquery_ui_slider (1.1.0 => 2.0.0):     Update of drupal/jquery_ui_slider failed
  - Upgrading drupal/jquery_ui_datepicker (1.1.0 => 2.0.0):     Update of drupal/jquery_ui_datepicker failed
  - Upgrading drupal/better_exposed_filters (5.0.0 => 6.0.3):     Update of drupal/better_exposed_filters failed
  - Upgrading drupal/colorbox (1.7.0 => 2.0.1):     Update of drupal/colorbox failed
  - Upgrading drupal/jquery_ui_checkboxradio (1.2.0 => 2.0.0):     Update of drupal/jquery_ui_checkboxradio failed
  - Upgrading drupal/search_api (1.21.0 => 1.29.0):     Update of drupal/search_api failed
`
It's not going to be easy to step through the composer script since this is happening in a build container, I don't get this error locally. I guess we need to try to imagine which commit could affect this check in the `doUpdate` method: `!$this->hasMetadataRepository($path) == TRUE`

**Comment by greg0ire** [comment]
So that build container… it already has a vendor directory with stuff in it? I see that you're not installing most packages, but upgrading them instead. Where do they come from before that call to `composer install`?

**Comment by greg0ire** [comment]
No answer… let's close this.

**Comment by stephenplatz** [comment]
I did answer, apparently email replies don’t show up here! In any case, what I said was that apparently the other non-changed dependencies are cached for the job, since I haven't overridden any default gitlab ci job variables. I guess I could try to turn that off, although I'm surprised that I need to, this hasn't come-up before with other dependency updates.

**Comment by greg0ire** [comment]
It is surprising indeed, but anyway, this is probably not the right place to report this. Maybe try your luck with Composer?
