### ISSUE TITLE
Add another backend for trigger_deprecations symfony

### ISSUE THREAD

**Issue by beberlei** [doctrine/deprecations#5]

**Comment by nicolas-grekas** [comment]
No need for that one - this lib doesn't collect the "version" that trigger_deprecation requires, and using trigger_error is just fine. KISS

**Comment by beberlei** [comment]
Yes I am even thinking to simplify this based on our discussion: Just have `enableWithSupressedTriggerError` and remove `enableWithTriggerError` and then "stack" loggers with trigger_error (i.e. you always add more, not overwrite the existing mode).

This would alleviate the concern that code bases are competing for each other for deprecation mode.
