### ISSUE TITLE
Add another mode for deduplication based on stacktrace

### ISSUE THREAD

**Issue by beberlei** [doctrine/deprecations#6]
We could add a second way for deduplication based on identifier + stacktrace. The stacktrace can be hashed using [fingerprinting rules](https://docs.sentry.io/platforms/rust/data-management/event-grouping/) from error tracking tools such as sentry.

Idea, user calls:

```php
Deprecation::includeStacktracesInDeduplication(true);
```

Then a deprecation is triggered once for every unique stacktrace it was triggered from.

**Comment by nicolas-grekas** [comment]
This is also better delegated to a custom error-handler or logger.
The dedup by link works, and is enough for Doctrine to keep up with perf.
